version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  app:
    container_name: code
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/code
    restart: always
